apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph-rbd
provisioner: kubernetes.io/rbd
parameters:
  monitors: 10.90.24.234:6789,10.90.24.129:6789,10.90.24.141:6789
  adminId: admin
# 指定secret
  adminSecretName: ceph-secret
#  adminSecretNamespace: comall   
  pool: ceshi #此处默认是rbd池，生产上建议自己创建存储池隔离
  userId: admin  # 对应secret的用户
  userSecretName: ceph-secret
# 以下指定rbd创建时镜像和文件系统的参数
#  fsType: xfs
#  imageFormat: "2"
#  imageFeatures: "layering"
