apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-default-2048
  namespace: default
spec:
  tls:
  - hosts:
    - 2048.kube.univer
    secretName: nginx-ssl-test
  rules:
  - host: 2048.kube.univer
    http:
      paths:
      - path: /
        backend:
          serviceName: app-2048
          servicePort: 80
